lockfileFilename: .yarn/yarn.lock

yarnPath: .yarn/releases/yarn-berry.cjs

logFilters:
  - code: YN0000
    level: discard
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard
  - code: YN0060
    level: discard
# nodeLinker: node-modules

