// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KeyBindTable: typeof import('./src/components/KeyBindTable.vue')['default']
    Readdir: typeof import('./src/components/Readdir.vue')['default']
  }
}

export { }
